name: Publish to MCP Registry

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (e.g., 1.0.1)'
        required: true
        type: string

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write  # Required for OIDC authentication

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          cache: true

      - name: Build and verify
        run: |
          go mod download
          go build -o bgg-mcp main.go
          echo "✓ Build successful"

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=tag
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Update server.json version
        run: |
          VERSION="${GITHUB_REF#refs/tags/v}"
          if [ -z "$VERSION" ]; then
            VERSION="${{ github.event.inputs.version }}"
          fi
          sed -i "s/\"version\": \"[^\"]*\"/\"version\": \"$VERSION\"/" server.json
          echo "Updated server.json to version $VERSION"

      - name: Validate server.json
        run: |
          chmod +x validate_server.sh
          ./validate_server.sh

      - name: Install MCP Publisher CLI
        run: |
          curl -fsSL https://github.com/modelcontextprotocol/mcp-cli/releases/latest/download/mcp-publisher-linux-x64 -o mcp-publisher
          chmod +x mcp-publisher
          sudo mv mcp-publisher /usr/local/bin/
          mcp-publisher --version

      - name: Publish to MCP Registry
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mcp-publisher login github --non-interactive
          mcp-publisher publish --non-interactive
          
          echo "✓ Successfully published to MCP Registry"
          echo "✓ Docker image published to: ghcr.io/kkjdaniel/bgg-mcp:${{ steps.meta.outputs.version }}"
          echo ""
          echo "Create a GitHub release manually with your release notes at:"
          echo "https://github.com/kkjdaniel/bgg-mcp/releases/new?tag=${{ github.ref_name }}"